Refactor code
iamargus95/GitHub_REST_API_consumer pull request #3
Opened 2021-09-08 08:21 UTC by iamargus95

Added tests for io.WriteToFile and changed githubapi.UserData and githubapi.RepoData to struct methods.

2021-09-08 20:14 UTC, iamargus95 commented
Added ability to parse usernames directly from the CLI.

2021-09-09 05:14 UTC, jdk2588 requested changes

2021-09-09 05:14 UTC, jdk2588 commented on githubapi/githubapi.go
> +const UrlGetRequest = "https://api.github.com/users/"
Constant are in CAPS https://golang.org/doc/effective_go#constants

2021-09-09 05:14 UTC, jdk2588 commented on githubapi/githubapi.go
> +	url := UrlGetRequest + username
Please use url constructor library, like https://pkg.go.dev/net/url

2021-09-09 05:14 UTC, jdk2588 commented on githubapi/githubapi.go
> +		url := UrlGetRequest + username + "/repos?type=public&per_page=100&page=" + strconv.Itoa(i)
Please use url constructor library, like https://pkg.go.dev/net/url

2021-09-09 05:14 UTC, jdk2588 commented on main.go
> +		io.WriteToFile(username, dataToFile)
Why write to file is outside of Go routine?

2021-09-09 05:14 UTC, jdk2588 commented on io/writeToFile.go
> +func WriteToFile(username string, dataToFile chan []string) error {
Write to File should only care about content like string data, should not use any channel.

2021-09-11 05:04 UTC, iamargus95 commented
Fixed Concurrency issues where data was being written to random files depending on which api call gives a faster response. Workaround :- Used a channel of map[string][]string to overcome it.

Fixed waitgroups not working as expected.  [ defer wg.Done() would not work inside the fetch worker func. ] 
Workaround :- Did a wg.Add(len(usernames)) before the write worker func.

Added Benckmarking tests and updated the README.

2021-09-11 07:36 UTC, merged